// Monochrome flowing ribbons and pointer grid, independent of content feeds.
(()=>{
const host=document.querySelector('.site-background');if(!host)return;
const canvas=document.createElement('canvas');canvas.className='pages-silver-background';canvas.setAttribute('aria-hidden','true');host.append(canvas);const ctx=canvas.getContext('2d');if(!ctx)return;
const motion=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover:hover) and (pointer:fine)');let w=0,h=0,frame=0,paused=false,last=0,time=0;
const pointer={x:0,y:0,alpha:0,inside:false};let pulses=[];
function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);draw()}
function draw(){ctx.clearRect(0,0,w,h);
for(let band=0;band<3;band++){
const cx=w*(.18+band*.35)+Math.sin(time*.22+band)*w*.06,cy=h*(.25+band*.22);
const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,w*.46);glow.addColorStop(0,'rgba(90,98,106,.09)');glow.addColorStop(1,'rgba(90,98,106,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
for(let i=0;i<16;i++){ctx.beginPath();for(let step=0;step<=48;step++){const x=w*step/48,y=cy+Math.sin(step/48*5+time*.32+band*1.9)*h*.14+Math.cos(step/48*8-time*.18)*h*.04+i*5;step?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=`rgba(88,97,107,${.045+Math.sin(i/16*Math.PI)*.095})`;ctx.lineWidth=i===8?1.1:.65;ctx.stroke()}}
if(fine.matches&&!motion.matches){pointer.alpha+=(Number(pointer.inside)-pointer.alpha)*.1;if(pointer.alpha>.005){ctx.save();ctx.beginPath();ctx.arc(pointer.x,pointer.y,160,0,Math.PI*2);ctx.clip();const g=ctx.createRadialGradient(pointer.x,pointer.y,0,pointer.x,pointer.y,160);g.addColorStop(0,`rgba(55,65,75,${.38*pointer.alpha})`);g.addColorStop(1,'rgba(55,65,75,0)');ctx.strokeStyle=g;ctx.lineWidth=1;const cell=64;for(let x=Math.floor((pointer.x-160)/cell)*cell;x<pointer.x+160;x+=cell){ctx.beginPath();ctx.moveTo(x,pointer.y-160);ctx.lineTo(x,pointer.y+160);ctx.stroke()}for(let y=Math.floor((pointer.y-160)/cell)*cell;y<pointer.y+160;y+=cell){ctx.beginPath();ctx.moveTo(pointer.x-160,y);ctx.lineTo(pointer.x+160,y);ctx.stroke()}ctx.restore()}
for(const p of pulses){const age=time-p.t;ctx.beginPath();ctx.arc(p.x,p.y,age*220+8,0,Math.PI*2);ctx.strokeStyle=`rgba(55,65,75,${Math.max(0,.3*(1-age/1.2))})`;ctx.lineWidth=1;ctx.stroke()}pulses=pulses.filter(p=>time-p.t<1.2)}}
function tick(now){frame=0;if(document.hidden||paused||motion.matches)return;if(now-last<33){frame=requestAnimationFrame(tick);return}time+=Math.min((now-last)/1000,.06);last=now;draw();frame=requestAnimationFrame(tick)}
function start(){if(!frame&&!document.hidden&&!paused&&!motion.matches){last=performance.now();frame=requestAnimationFrame(tick)}}
addEventListener('pointermove',e=>{if(e.pointerType==='mouse'&&fine.matches){pointer.x=e.clientX;pointer.y=e.clientY;pointer.inside=true}},{passive:true});document.documentElement.addEventListener('pointerleave',()=>pointer.inside=false);addEventListener('blur',()=>pointer.inside=false);addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&fine.matches&&!motion.matches&&!paused){pulses.push({x:e.clientX,y:e.clientY,t:time});pulses=pulses.slice(-5)}},{passive:true});
const control=document.createElement('button');control.className='background-motion-control pages-background-control';control.textContent='Pause background';control.setAttribute('aria-pressed','false');document.body.append(control);control.addEventListener('click',()=>{paused=!paused;control.textContent=paused?'Play background':'Pause background';control.setAttribute('aria-pressed',String(paused));if(paused){cancelAnimationFrame(frame);frame=0}else start()});
function preference(){control.hidden=motion.matches;if(motion.matches){cancelAnimationFrame(frame);frame=0;pulses=[];draw()}else start()}motion.addEventListener('change',preference);fine.addEventListener('change',()=>{pointer.inside=false;pulses=[]});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(frame);frame=0}else start()});addEventListener('resize',resize);resize();preference();
})();
const base=new URL('.',import.meta.url).pathname.replace(/\/$/,'');
const local=p=>base+p;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const data=await fetch(local('/data/portfolio.json')).then(r=>r.json());
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Accessible native disclosures and keyboard closing.
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.native-menu[open]').forEach(n=>{n.open=false;n.querySelector('summary').focus()})});
for(const ecosystem of document.querySelectorAll('.ecosystem')){const buttons=ecosystem.querySelectorAll('.command-tabs button');for(const button of buttons)button.addEventListener('click',()=>{const group=button.textContent.trim();buttons.forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});const grid=ecosystem.querySelector('.tech-grid');grid.innerHTML=(data.skills[group]||[]).map(t=>`<div class="tech-node" title="${esc(t)}"><span class="tech-symbol" aria-hidden="true">${data.icons[t]?`<img src="${local(data.icons[t])}" alt="" width="24" height="24" loading="lazy">`:'◇'}</span><strong>${esc(t)}</strong><span class="tech-category">${esc(group)}</span></div>`).join('')})}
if(!reduced){const specialty=document.querySelector('.specialty>span:last-child');if(specialty){const areas=['Technical Writing','Data Analytics','AI & Machine Learning','Web Development','Custom CRM','Digital Marketing','Social Media Branding'];let i=0;setInterval(()=>{specialty.textContent=areas[++i%areas.length]},3200)}const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.animate([{opacity:.55,transform:'translateY(12px)'},{opacity:1,transform:'none'}],{duration:500,easing:'ease-out'});observer.unobserve(e.target)}}));document.querySelectorAll('.section-heading,.career-timeline article,.sample-cover').forEach(e=>observer.observe(e));}
// Local collection filters and search work without server query routes.
function collection(kind){const article=kind==='articles',cards=[...document.querySelectorAll(article?'.article-card':'.repo-card,.project-card')],input=document.querySelector(article?'#article-search':'#project-search');if(!input)return;const query=new URLSearchParams(location.search);let source=query.get('source')||'All',category=query.get('category')||'All';const filters=[...document.querySelectorAll('.filters a')];
function apply(){let count=0;cards.forEach(card=>{const text=card.textContent.toLowerCase(),title=card.querySelector('h3')?.textContent?.trim()||'';const item=article?data.articles.find(a=>a.title===title):null;const cat=article?(item?.category||card.querySelector('.article-topic')?.textContent):(card.querySelector('.eyebrow')?.textContent||'');const publication=item?.source||card.querySelector('.eyebrow')?.textContent||'';const visible=text.includes(input.value.trim().toLowerCase())&&(category==='All'||String(cat).toLowerCase().includes(category.toLowerCase()))&&(!article||source==='All'||publication.includes(source));card.hidden=!visible;if(visible)count++});const status=input.closest('.collection-search')?.querySelector('[role="status"]');if(status)status.textContent=count+' '+(article?'articles':'projects')+' match your selection.';filters.forEach(a=>{const u=new URL(a.href),isCategory=a.closest('.category-filters')||!article;const selected=isCategory?category:source;const value=u.searchParams.get(isCategory?'category':'source')||'All';a.classList.toggle('active',selected===value);if(selected===value)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')})}
input.addEventListener('input',apply);filters.forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const u=new URL(a.href),isCategory=a.closest('.category-filters')||!article;if(isCategory)category=u.searchParams.get('category')||'All';else source=u.searchParams.get('source')||'All';const q=new URLSearchParams();if(article)q.set('source',source);q.set('category',category);history.replaceState(null,'',location.pathname+'?'+q);apply()}));apply()}
collection('articles');collection('projects');
// Contact is a real, clearly labelled mailto workflow on static hosting.
const form=document.querySelector('.contact-form');if(form){const params=new URLSearchParams(location.search),select=form.querySelector('[name="service"]'),service=params.get('service'),map={writing:'Technical writing',data:'Research & data analytics',web:'Website / web application',crm:'Customised CRM',marketing:'Digital marketing / branding',social:'Digital marketing / branding'};if(service&&[...select.options].some(o=>o.value===(map[service]||service)))select.value=map[service]||service;const message=form.querySelector('[name="message"]'),counter=form.querySelector('.message-counter');message.addEventListener('input',()=>{if(counter)counter.textContent=message.value.length+' / 5,000 characters.'});for(const b of form.querySelectorAll('button[type="button"]'))b.addEventListener('click',async()=>{if(b.textContent.includes('brief template')){message.value='Service: '+select.value+'\n\nProject goal and audience:\n\nRequired deliverables or word count:\n\nAvailable material / referencing style:\n\nPreferred deadline and time zone:\n\nBudget range (optional):';message.dispatchEvent(new Event('input'));message.focus()}else{try{await navigator.clipboard.writeText('soumiganguly2021@gmail.com');b.textContent='Email copied'}catch{b.textContent='soumiganguly2021@gmail.com'}}});form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));const body='Name: '+values.name+'\nReply email: '+values.email+'\nService: '+values.service+'\n\n'+values.message;location.href='mailto:soumiganguly2021@gmail.com?subject='+encodeURIComponent('Portfolio enquiry: '+values.service)+'&body='+encodeURIComponent(body);const status=form.querySelector('[aria-live="polite"]');if(status)status.textContent='Your email application should open. Review the message and press Send. You can also use the direct email link below.'})}
// Bundled PDF.js viewer: no print or download buttons.
const canvas=document.querySelector('.pdf-reader canvas');if(canvas){const id=location.pathname.split('/').filter(Boolean).pop(),sample=data.samples.find(s=>s.id===id),reader=canvas.closest('.pdf-reader'),controls=reader.querySelector('.pdf-reader-controls'),previous=controls.querySelector('button:first-child'),next=controls.querySelector('button:last-child'),jump=controls.querySelector('input'),label=controls.querySelector('[aria-live]');let pdf,page=1,task;
async function render(){try{if(task){task.cancel();try{await task.promise}catch{}}const p=await pdf.getPage(page),original=p.getViewport({scale:1}),width=Math.min(canvas.parentElement.clientWidth,1000),viewport=p.getViewport({scale:width/original.width}),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(viewport.width*dpr);canvas.height=Math.floor(viewport.height*dpr);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';canvas.setAttribute('aria-label',sample.title+', page '+page);previous.disabled=page<=1;next.disabled=page>=pdf.numPages;jump.disabled=false;jump.max=pdf.numPages;jump.value=page;label.textContent=(sample.format==='presentation'?'Slide ':'Page ')+page+' of '+pdf.numPages;task=p.render({canvas,canvasContext:canvas.getContext('2d'),viewport,transform:dpr!==1?[dpr,0,0,dpr,0,0]:undefined});await task.promise}catch(e){if(e.name!=='RenderingCancelledException')label.textContent='This page could not be displayed. Please reload.'}}
try{if(!sample)throw Error('Unknown sample');const pdfjs=await import(local('/vendor/pdf.mjs'));pdfjs.GlobalWorkerOptions.workerSrc=local('/vendor/pdf.worker.mjs');pdf=await pdfjs.getDocument({url:local(sample.asset),cMapUrl:local('/vendor/cmaps/'),cMapPacked:true,standardFontDataUrl:local('/vendor/standard_fonts/'),wasmUrl:local('/vendor/wasm/'),isEvalSupported:false}).promise;previous.addEventListener('click',()=>{if(page>1){page--;render()}});next.addEventListener('click',()=>{if(page<pdf.numPages){page++;render()}});jump.addEventListener('change',()=>{const n=Number(jump.value);if(Number.isInteger(n)&&n>=1&&n<=pdf.numPages){page=n;render()}else jump.value=page});new ResizeObserver(()=>render()).observe(canvas.parentElement);await render()}catch{label.textContent='The sample could not load. Please reload or contact Soumi.'}}
// Draggable workspace handles retain keyboard operation and reset controls.
for(const handle of document.querySelectorAll('.drag-handle')){const panel=handle.closest('.os-window');let x=0,y=0,start;const move=()=>{panel.style.transform=`translate(${x}px,${y}px)`};handle.addEventListener('keydown',e=>{const delta={ArrowLeft:[-8,0],ArrowRight:[8,0],ArrowUp:[0,-8],ArrowDown:[0,8]}[e.key];if(delta){e.preventDefault();x=Math.max(-45,Math.min(45,x+delta[0]));y=Math.max(-35,Math.min(35,y+delta[1]));move()}});handle.addEventListener('pointerdown',e=>{start=[e.clientX,e.clientY,x,y];handle.setPointerCapture(e.pointerId)});handle.addEventListener('pointermove',e=>{if(start){x=Math.max(-45,Math.min(45,start[2]+e.clientX-start[0]));y=Math.max(-35,Math.min(35,start[3]+e.clientY-start[1]));move()}});handle.addEventListener('pointerup',()=>start=null);panel.querySelector('.window-reset')?.addEventListener('click',()=>{x=y=0;move()})}
for(const head of document.querySelectorAll('.branched-menu__head'))head.addEventListener('click',()=>{const section=head.closest('.branched-menu__section'),open=head.getAttribute('aria-expanded')==='true';head.setAttribute('aria-expanded',String(!open));section.toggleAttribute('data-open',!open);section.querySelector('.branched-menu__body').hidden=open});
const orbit=document.querySelector('.orbit-static');if(orbit){orbit.classList.add('pages-orbit');[...orbit.querySelectorAll('img')].forEach((im,i,a)=>{const angle=i/a.length*Math.PI*2;im.style.left=(50+34*Math.cos(angle))+'%';im.style.top=(50+34*Math.sin(angle))+'%'});const button=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='Pause orbit');button?.addEventListener('click',()=>{const paused=orbit.classList.toggle('paused');button.textContent=paused?'Play orbit':'Pause orbit';button.setAttribute('aria-pressed',String(paused))})}
