// Free portfolio assistant. Local answers; no API key or external AI calls.
(()=>{const root=new URL('.',document.currentScript.src);const url=p=>new URL(p,root).href;
const style=document.createElement('link');style.rel='stylesheet';style.href=url('portfolio-chat.css');document.head.append(style);
const shell=document.createElement('div');shell.className='soumi-chat';shell.innerHTML=`<button class="chat-launch" aria-label="Open portfolio assistant" aria-expanded="false"><svg viewBox="0 0 80 80" aria-hidden="true"><path d="M40 10v9" stroke="white" stroke-width="4"/><circle cx="40" cy="8" r="5" fill="#ddd"/><rect x="12" y="20" width="56" height="44" rx="17" fill="#f0f0f0"/><rect x="5" y="32" width="7" height="18" rx="3" fill="#aaa"/><rect x="68" y="32" width="7" height="18" rx="3" fill="#aaa"/><circle cx="29" cy="39" r="6" fill="#222"/><circle cx="51" cy="39" r="6" fill="#222"/><circle cx="31" cy="37" r="2" fill="white"/><circle cx="53" cy="37" r="2" fill="white"/><path d="M29 52q11 10 22 0" stroke="#333" stroke-width="3" fill="none"/><path d="M22 64l-3 9 17-9" fill="#eee"/></svg></button><section class="chat-panel" aria-label="Portfolio assistant" hidden><header><div><strong>Soumi’s portfolio assistant</strong><small>Free guide · portfolio answers</small></div><button class="chat-close" aria-label="Close assistant">×</button></header><div class="chat-messages" role="log" aria-live="polite" aria-relevant="additions"></div><div class="chat-prompts"><button>Services</button><button>Writing samples</button><button>Research support</button><button>Contact</button></div><form><label class="chat-label" for="portfolio-chat-input">Your question</label><input id="portfolio-chat-input" maxlength="600" placeholder="Ask about Soumi’s work…" autocomplete="off" required><button type="submit">Send</button></form><p class="chat-disclosure">Automated portfolio guide. General questions, quotes and availability need Soumi’s confirmation.</p></section>`;document.body.append(shell);
const launch=shell.querySelector('.chat-launch'),panel=shell.querySelector('.chat-panel'),input=shell.querySelector('input'),log=shell.querySelector('.chat-messages'),send=shell.querySelector('[type="submit"]');
function message(text,who='assistant',links=[]){const el=document.createElement('div');el.className='chat-message '+who;const p=document.createElement('p');p.textContent=text;el.append(p);for(const [label,path]of links){const a=document.createElement('a');a.textContent=label;a.href=url(path);el.append(a)}log.append(el);log.scrollTop=log.scrollHeight;return el}
function open(value){panel.hidden=!value;launch.setAttribute('aria-expanded',String(value));if(value)input.focus();else launch.focus()}
launch.addEventListener('click',()=>open(panel.hidden));shell.querySelector('.chat-close').addEventListener('click',()=>open(false));shell.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)open(false)});
message('Hello! I can help you explore Soumi’s writing, research support, data analysis and digital services. What do you need?');
const topics=[
{terms:'services service help hire কাজ সাহায্য',answer:'Soumi offers technical writing, research guidance and editing, data analytics, AI/ML, website and web app development, custom CRM, digital marketing and social media branding. Tell me which service interests you.',links:[['Explore services','services/'],['Discuss a project','contact/']]},
{terms:'writing writer technical documentation seo content article লেখ',answer:'Soumi’s primary focus is technical content writing, with 4+ years of experience in research-based articles, documentation and SEO content. Explore writing samples or published articles.',links:[['Writing samples','writing/'],['Published articles','articles/']]},
{terms:'sample pdf document samples portfolio নমুনা',answer:'The writing section includes 23 documents in an on-site viewer. The viewer has no download or print buttons, although public files can still be saved by visitors.',links:[['View writing samples','writing/']]},
{terms:'assignment dissertation thesis student research academic literature methodology referencing proofreading editing university ছাত্র',answer:'Research support includes assignment planning and draft feedback, dissertation/thesis guidance, literature review and methodology support, academic editing, referencing and analysis. Share your brief and current work; you retain responsibility for authorship and submission.',links:[['Academic support','academic-research-support/'],['Dissertation & thesis','dissertation-thesis-support/']]},
{terms:'spss python r statistics statistical analysis data tableau power bi excel regression analytics dataset',answer:'You can discuss SPSS, R, Python, SQL, Excel, Tableau and Power BI support, including data preparation, visualisation, statistics and research interpretation. Methods and scope depend on your data and questions.',links:[['Research data analysis','student-data-analysis/'],['Data & AI','data-ai/']]},
{terms:'ai ml machine learning computer vision yolo pytorch forecasting model',answer:'Soumi’s portfolio includes machine learning, computer vision, forecasting and analytical research. Explore the projects and discuss your dataset, aim and required deliverables.',links:[['Data & AI','data-ai/'],['Projects','projects/']]},
{terms:'website web app application development developer react html css site',answer:'Website and web application services cover responsive websites, interfaces and tailored workflows. Send your goals, required features, existing assets and timeline for a scope discussion.',links:[['Web development','web-development/'],['Contact Soumi','contact/']]},
{terms:'crm custom customized customised customer lead pipeline automation',answer:'Customised CRM work can address lead capture, customer records, sales pipelines, tasks, reporting and integration requirements. Describe your current workflow and team needs.',links:[['Custom CRM','crm/']]},
{terms:'marketing digital campaign brand branding social media instagram facebook promotion',answer:'Digital marketing and social branding support includes audience-focused messaging, SEO content planning, campaign briefs, brand voice and content calendars. Share your channels and business goals.',links:[['Digital marketing','digital-marketing/'],['Social branding','social-branding/']]},
{terms:'price pricing quote cost budget fee rate payment টাকা কত',answer:'Prices are not fixed in the portfolio. Contact Soumi with the scope, deadline and budget to request a quote. I cannot confirm fees, availability or delivery dates.',links:[['Request a quote','contact/']]},
{terms:'contact email phone whatsapp number book meeting যোগাযোগ mail',answer:'Use the Contact page to send your project brief. Its form prepares an email draft; you need to send it through your email application. No enquiry is booked through this chat.',links:[['Contact Soumi','contact/']]},
{terms:'education degree mba btech diploma ignou mckv পড়াশোনা',answer:'Education: B.Tech in Computer Science & Engineering (Data Science), MCKV Institute of Engineering, 2022–2026; MBA in Operations Management, IGNOU, 2026–Present; Diploma in Computer Science Engineering, 2019–2022.',links:[['Education','education/']]},
{terms:'experience career background about soumi who',answer:'Soumi Ganguly combines technical writing with research, data analytics and digital development. For the complete professional background, use the About and Experience pages.',links:[['About Soumi','about/'],['Experience','experience/']]},
{terms:'uk usa india abroad international country remote london america বিদেশ',answer:'Remote enquiries are welcome from India, the UK, the USA and other countries. Share your time zone, requirements and deadline. This describes service availability, not overseas office locations.',links:[['International services','international-services/'],['Contact','contact/']]}
];
function answer(q){const clean=q.toLowerCase();if(/^(hi|hello|hey|হাই|নমস্কার)[! .]*$/.test(clean))return{answer:'Hello! Ask about services, samples, research support, projects or contacting Soumi.',links:[]};const words=clean.split(/[^\p{L}\p{N}]+/u).filter(w=>w.length>1);const ranked=topics.map(t=>({t,score:words.reduce((n,w)=>n+(t.terms.split(' ').includes(w)?1:0),0)})).sort((a,b)=>b.score-a.score);if(!ranked[0].score)return{answer:'I can answer questions about this portfolio and its services. I do not have a live AI connection or reliable answers to general questions. For your specific enquiry, contact Soumi directly.',links:[['Contact Soumi','contact/']]};return ranked[0].t}
function ask(q){if(!q.trim())return;message(q,'visitor');const result=answer(q);message(result.answer,'assistant',result.links);input.value=''}shell.querySelector('form').addEventListener('submit',e=>{e.preventDefault();ask(input.value)});shell.querySelectorAll('.chat-prompts button').forEach(b=>b.addEventListener('click',()=>ask(b.textContent)));
})();
