import {readFile,writeFile} from 'node:fs/promises';
const json=async f=>JSON.parse(await readFile('data/'+f,'utf8'));
const decode=s=>String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n)));
const clean=s=>decode(s.replace(/<[^>]*>/g,'')).trim();
const field=(s,key)=>decode(s.match(new RegExp('<'+key+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+key+'>'))?.[1]||'');
const get=async u=>{const r=await fetch(u,{headers:{'User-Agent':'SoumiPortfolioContentSync/1.0'},signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(r.status+' '+u);return r};
try{const xml=await (await get('https://medium.com/feed/@soumiganguly2021')).text(),items=[],docs=await json('article-documents.json');for(const m of xml.matchAll(/<item>([\s\S]*?)<\/item>/g)){const raw=m[1],url=field(raw,'link').split('?')[0],id=url.match(/([a-f0-9]{12})(?:$|\/)/)?.[1],title=field(raw,'title'),body=field(raw,'content:encoded');if(!id||!/^https:\/\//.test(url)||!title)continue;const blocks=[];for(const b of body.matchAll(/<(p|h[1-6]|li|blockquote|pre)\b[^>]*>([\s\S]*?)<\/\1>|<img\b([^>]+)>/gi)){if(b[3]){const src=b[3].match(/src=["']([^"']+)/)?.[1];if(src&&/^https:\/\//.test(src))blocks.push({kind:'image',text:decode(src),alt:clean(b[3].match(/alt=["']([^"']*)/)?.[1]||'')})}else{const text=clean(b[2]);if(text)blocks.push({kind:b[1].startsWith('h')?'h2':'p',text})}}const d={id,title,url,blocks},index=docs.findIndex(x=>x.id===id);if(index<0)docs.push(d);else docs[index]=d;const date=field(raw,'pubDate'),parsed=new Date(date);items.push({title,url,source:'Medium',...(Number.isFinite(parsed.getTime())?{date:parsed.toISOString().slice(0,10)}:{}),readerId:id,image:blocks.find(b=>b.kind==='image')?.text||'',excerpt:blocks.find(b=>b.kind==='p')?.text.slice(0,240)||''})}if(!items.length)throw Error('No valid Medium items');const old=await json('medium-snapshot.json');const merged=[...items,...old].filter((x,i,a)=>a.findIndex(y=>y.readerId===x.readerId)===i);await writeFile('data/medium-snapshot.json',JSON.stringify(merged,null,2));await writeFile('data/article-documents.json',JSON.stringify(docs,null,2));console.log('Medium refreshed:',items.length)}catch(e){console.warn('Medium unavailable; retained existing articles:',e.message)}
try{const repos=[];for(let page=1;page<=10;page++){const batch=await (await get('https://api.github.com/users/Soumi19/repos?per_page=100&sort=updated&page='+page)).json();repos.push(...batch.filter(r=>!r.private));if(batch.length<100)break}if(!repos.length)throw Error('No public repositories');await writeFile('data/github-snapshot.json',JSON.stringify(repos,null,2));console.log('GitHub refreshed:',repos.length)}catch(e){console.warn('GitHub unavailable; retained projects:',e.message)}
// Only use publicly accessible article headings from the existing author profile.
try{const html=await (await get('https://muckrack.com/soumi-ganguly-1/articles')).text(),items=[];for(const m of html.matchAll(/<h[34]\b[^>]*>[\s\S]*?<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>[\s\S]*?<\/h[34]>/gi)){const url=decode(m[1]),title=clean(m[2]);if(!/^https:\/\//.test(url)||/muckrack\.com/.test(url)||title.length<20)continue;items.push({title,url,source:'Muck Rack',excerpt:'Published writing listed on Soumi Ganguly’s author profile. Read the original publication.',image:''})}if(items.length){const old=await json('additional-publications.json');await writeFile('data/additional-publications.json',JSON.stringify([...items,...old].filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i),null,2));console.log('Muck Rack public listing refreshed:',items.length)}else console.warn('Muck Rack did not expose a readable listing; retained verified publication links.')}catch(e){console.warn('Muck Rack unavailable; retained publication links:',e.message)}
